-- =========================================================
-- T_DEPARTMENT — 부서 (조직 계층: PARENT_DEPT_ID 자기참조)
-- 선행: functions/F_AUDIT_LOG.sql
-- =========================================================
create table T_DEPARTMENT (
    DEPT_ID        bigint        generated by default as identity,
    DEPT_UUID      uuid          not null default gen_random_uuid(),
    DEPT_NAME      varchar(100)  not null,
    PARENT_DEPT_ID bigint,                          -- 상위 부서 (조직 계층)
    USE_YN         char(1)       not null default 'Y',
    CREATED_ON     timestamptz   not null default current_timestamp,
    CREATED_BY     bigint,
    UPDATED_ON     timestamptz,
    UPDATED_BY     bigint,
    --
    constraint PK_T_DEPARTMENT primary key (DEPT_ID),
    constraint UNQ_T_DEPARTMENT_UUID unique (DEPT_UUID),
    constraint FK_T_DEPARTMENT_PARENT_DEPT_ID foreign key (PARENT_DEPT_ID) references T_DEPARTMENT (DEPT_ID),
    constraint CK_T_DEPARTMENT_USE_YN check (USE_YN in ('Y', 'N'))
);

create trigger T_DEPARTMENT_TRG
    before insert or update on T_DEPARTMENT
    for each row execute function F_AUDIT_LOG();

create index IDX_T_DEPARTMENT_PARENT_DEPT_ID on T_DEPARTMENT (PARENT_DEPT_ID);
