-- =========================================================
-- T_EMPLOYEE — 직원
-- 선행: functions/F_AUDIT_LOG.sql, tables/T_DEPARTMENT.sql, tables/T_POSITION.sql
-- =========================================================
create table T_EMPLOYEE (
    EMP_ID      bigint        generated by default as identity,
    EMP_UUID    uuid          not null default gen_random_uuid(),
    EMP_NO      varchar(20)   not null,             -- 사번
    EMP_NAME    varchar(100)  not null,
    EMAIL       varchar(255),
    PHONE       varchar(20),
    HIRE_DATE   date          not null,
    DEPT_ID     bigint,
    POSITION_ID bigint,
    MANAGER_ID  bigint,                             -- 직속 상사 (자기참조)
    EMP_STATUS  varchar(10)   not null default 'ACTIVE',  -- ACTIVE/LEAVE/RESIGNED
    CREATED_ON  timestamptz   not null default current_timestamp,
    CREATED_BY  bigint,
    UPDATED_ON  timestamptz,
    UPDATED_BY  bigint,
    --
    constraint PK_T_EMPLOYEE primary key (EMP_ID),
    constraint UNQ_T_EMPLOYEE_UUID unique (EMP_UUID),
    constraint UNQ_T_EMPLOYEE_EMP_NO unique (EMP_NO),
    constraint FK_T_EMPLOYEE_DEPT_ID foreign key (DEPT_ID) references T_DEPARTMENT (DEPT_ID),
    constraint FK_T_EMPLOYEE_POSITION_ID foreign key (POSITION_ID) references T_POSITION (POSITION_ID),
    constraint FK_T_EMPLOYEE_MANAGER_ID foreign key (MANAGER_ID) references T_EMPLOYEE (EMP_ID),
    constraint CK_T_EMPLOYEE_STATUS check (EMP_STATUS in ('ACTIVE', 'LEAVE', 'RESIGNED'))
);

create trigger T_EMPLOYEE_TRG
    before insert or update on T_EMPLOYEE
    for each row execute function F_AUDIT_LOG();

create index IDX_T_EMPLOYEE_DEPT_ID     on T_EMPLOYEE (DEPT_ID);
create index IDX_T_EMPLOYEE_POSITION_ID on T_EMPLOYEE (POSITION_ID);
create index IDX_T_EMPLOYEE_MANAGER_ID  on T_EMPLOYEE (MANAGER_ID);
create index IDX_T_EMPLOYEE_EMP_STATUS  on T_EMPLOYEE (EMP_STATUS);
