-- =========================================================
-- T_EMPLOYMENT_HISTORY — 인사 발령 이력 (입사/이동/승진/휴직/복직/퇴직)
-- 선행: functions/F_AUDIT_LOG.sql, tables/T_EMPLOYEE.sql, T_DEPARTMENT.sql, T_POSITION.sql
-- =========================================================
create table T_EMPLOYMENT_HISTORY (
    HISTORY_ID     bigint        generated by default as identity,
    HISTORY_UUID   uuid          not null default gen_random_uuid(),
    EMP_ID         bigint        not null,
    CHANGE_TYPE    varchar(20)   not null,          -- HIRE/TRANSFER/PROMOTION/LEAVE/RETURN/RESIGN
    DEPT_ID        bigint,                            -- 발령 후 부서
    POSITION_ID    bigint,                            -- 발령 후 직급
    EFFECTIVE_DATE date          not null,
    REMARK         varchar(500),
    CREATED_ON     timestamptz   not null default current_timestamp,
    CREATED_BY     bigint,
    UPDATED_ON     timestamptz,
    UPDATED_BY     bigint,
    --
    constraint PK_T_EMPLOYMENT_HISTORY primary key (HISTORY_ID),
    constraint UNQ_T_EMPLOYMENT_HISTORY_UUID unique (HISTORY_UUID),
    constraint FK_T_EMP_HISTORY_EMP_ID foreign key (EMP_ID) references T_EMPLOYEE (EMP_ID),
    constraint FK_T_EMP_HISTORY_DEPT_ID foreign key (DEPT_ID) references T_DEPARTMENT (DEPT_ID),
    constraint FK_T_EMP_HISTORY_POSITION_ID foreign key (POSITION_ID) references T_POSITION (POSITION_ID),
    constraint CK_T_EMP_HISTORY_CHANGE_TYPE check (CHANGE_TYPE in ('HIRE', 'TRANSFER', 'PROMOTION', 'LEAVE', 'RETURN', 'RESIGN'))
);

create trigger T_EMPLOYMENT_HISTORY_TRG
    before insert or update on T_EMPLOYMENT_HISTORY
    for each row execute function F_AUDIT_LOG();

create index IDX_T_EMP_HISTORY_EMP_ID    on T_EMPLOYMENT_HISTORY (EMP_ID);
create index IDX_T_EMP_HISTORY_EFFECTIVE on T_EMPLOYMENT_HISTORY (EFFECTIVE_DATE);
