-- =========================================================
-- T_POSITION — 직급 (사원/대리/과장/차장/부장 …)
-- 선행: functions/F_AUDIT_LOG.sql
-- =========================================================
create table T_POSITION (
    POSITION_ID    bigint        generated by default as identity,
    POSITION_UUID  uuid          not null default gen_random_uuid(),
    POSITION_NAME  varchar(50)   not null,          -- 직급명
    POSITION_LEVEL smallint      not null,          -- 서열·정렬용 (1=사원 …)
    USE_YN         char(1)       not null default 'Y',
    CREATED_ON     timestamptz   not null default current_timestamp,
    CREATED_BY     bigint,
    UPDATED_ON     timestamptz,
    UPDATED_BY     bigint,
    --
    constraint PK_T_POSITION primary key (POSITION_ID),
    constraint UNQ_T_POSITION_UUID unique (POSITION_UUID),
    constraint UNQ_T_POSITION_NAME unique (POSITION_NAME),
    constraint CK_T_POSITION_USE_YN check (USE_YN in ('Y', 'N'))
);

create trigger T_POSITION_TRG
    before insert or update on T_POSITION
    for each row execute function F_AUDIT_LOG();
